name = "floyo-api"
main = "src/worker.js"
compatibility_date = "2024-06-01"

[vars]
ENVIRONMENT = "production"
APP_NAME = "floyo-api"
SCAN_CRON = "0 3 * * *"
LOG_LEVEL = "INFO"

[[d1_databases]]
binding = "DB"
database_name = "floyo"
database_id = "af69a9c9-a721-4d3c-b17b-f937c4057472"

[triggers]
crons = ["0 3 * * *"]

[[routes]]
pattern = "audit.example.com"
custom_domain = true
